# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 温风·如酒
subtitle:
# 路漫漫其修远兮，吾将上下而求索
description:
# 站在巨人的肩膀上
author: 小成
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://talengu.github.io
root: /public
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 3
pagination_dir: page

# Extensions
#Plugins:
#  hexo-generator-feed
#  hexo-generator-search

#Feed Atom
feed:
 type: atom
 path: atom.xml
 limit: 20

##Search talen cancel
#search:
#  path: search.xml
#  field: post
# talen add here
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

## lived2d
## https://github.com/EYHN/hexo-helper-live2d
## npm install --save hexo-helper-live2d
## npm install --save live2d-widget-model-hijiki
## models https://github.com/xiazeyu/live2d-widget-models
## models demo :https://huaji8.top/post/live2d-plugin-2.0/

live2d:
  enable: true
  scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js
  tagMode: true
  log: false
  model:
    use: live2d-widget-model-hijiki
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 75
    height: 150
    position: right
    hOffset: 0
    vOffset: 0
  mobile:
    show: true
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
#  repository: https://github.com/talengu/talengu.github.io.git
#  branch: public
